# Generated by Django 5.1.3 on 2024-11-25 19:14

import college_api.models
import college_api.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB, formats: jpg, jpeg, png, gif)', null=True, upload_to=college_api.utils.get_profile_pic_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), college_api.models.validate_file_size]),
        ),
    ]
